### ISSUE TITLE
Update for Laravel 4.1?

### ISSUE THREAD

**Issue by pidgpowell** [hanl/laravel-google-auth#1]
Hi. I tried updating the dependency for illuminate/support in composer.json to ~4 but I think there's something else not working within the package as, while i can login via google, the user object is empty. Any ideas? Thanks,

Mark

**Comment by felthy** [comment]
When we receive the `code` GET parameter from google, the `GoogleUserProvider` constructor stores an access token in the session, sets a `Location` header (to redirect the user to their intended destination) and calls `exit()`.
In Laravel 4.0 this worked but in 4.1 the `exit()` call skips the code in the new `\Illuminate\Session\Middleware` class that writes the updated session.

We need to find a new way to cleanly abort the request while still allowing the session to be updated successfully.

**Comment by felthy** [comment]
Note that the fix involves a slight change to your code - you will need to add a route filter to the route that receives the redirect from google. See the _Usage_ section of the updated [README.md](https://github.com/TheMonkeys/laravel-google-auth/blob/master/README.md) for details.
