### ISSUE TITLE
Restrict To Single Domain / GApps Organization?

### ISSUE THREAD

**Issue by wykydtronik** [hanl/laravel-google-auth#12]
Just curious, is there a way to restrict to a single domain? For example, if you have a GApps for Business account and the client want's their staff want to access a custom dashboard they can auth with their gapps account? While users outside of their gapps can't access?

**Comment by felthy** [comment]
Yep, the `Auth::user()->hd` field will give you the user's hosted domain, so you can check that when deciding whether to grant or deny access to something. This library authenticates users but authorisation is up to you.
